name: Todoer Task Manager Release (Deploy to GCP)

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: SSH and Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_IP }}
          username: josegarrera
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            docker stop task-manager || true
            docker rm task-manager || true
            docker pull josegarrera/task-manager:${{ github.sha }}
            docker run -d --name task-manager -p 3000:3000 josegarrera/task-manager:${{ github.sha }}
